### ISSUE TITLE
Grey Knight bugs

### ISSUE THREAD

**Issue by Genx3000** [BSData/TemplateDataRepo#11]
**Describe the bug**
There is description for enhancements and when they are selected no information is provided in the preview of that character

**To Reproduce**
1.  Create grey Knight roster
2.  Add detachment to configuration tab
3.  Select teleport strike force
4.  Add grand master in nemesis dreadknight
5.  Open character select any enhancements
6. Preview character

**Expected behavior**
Should see enhancement with description in the preview of the character

**Screenshots**
I
![Screenshot_20230727_171411](https://github.com/BSData/TemplateDataRepo/assets/140737428/07d5a05b-31b9-48f4-aa8d-aebd130380eb)
![Screenshot_20230727_171354](https://github.com/BSData/TemplateDataRepo/assets/140737428/ef50ba8e-e48f-4895-806c-6684ff342908)
![Screenshot_20230727_171347](https://github.com/BSData/TemplateDataRepo/assets/140737428/be81ad28-f8a7-4c30-9334-3b9b42e470e1)

**Device and data (please complete the following information):**
 - OS: android
 - Battlescribe
 - App version
 - Data release version 10.02

**Comment by Mad-Spy** [comment]
Please raise your issue in the correct repository.
