### ISSUE TITLE
Desolation marine squad size

### ISSUE THREAD

**Issue by Pascalben123** [BSData/TemplateDataRepo#3]
**Describe the bug**
Desolation marines have a beginning unit limit of 4, battlescribe is saying that there is only 1 desolation marine allowed

**To Reproduce**
1. Put a desolation marine squad into your army
2. See error

**Expected behavior**
The expected behavior of this is that it doesnt kick back an error about the minimum squad size

**Screenshots**
![image_2023-07-24_143943832](https://github.com/BSData/TemplateDataRepo/assets/140405855/3265d154-0b09-481d-81d4-fee39370d110)

**Device and data (please complete the following information):**
 - OS: Windows
 - BattleScribe version [2.03.21]
 - Release version [e.g. v10.0.0]

**Additional context**

**Comment by Mad-Spy** [comment]
Please raise your issue in the correct repository.
