### ISSUE TITLE
Some issues noticed with Black Templars/Space Marine units

### ISSUE THREAD

**Issue by Slippingdownside** [BSData/TemplateDataRepo#6]
Sorry if some of these have already been pointed out, just trying to help in any way that I can!
1. Captain in Terminator armor can't be the Warlord in app
2. Black Templar Enhancements don't cost any points when they should
3. App keeps telling me that I need to have evert Blood Angels Enhancements selected when I have Righteous Crusaders Detachment selected
4. The Gladiator tanks don't show up at all as a selectable unit
5. The Kratos Tank is 20 points cheaper than it should be

Again, sorry if these are already known issues, and thank you for still putting effort into Battlescribe!

**Comment by Mad-Spy** [comment]
Please raise your issue in the correct repository.
